Support config and context parameters
TileDB-Inc/tiledbsc pull request #47
Opened 2022-04-26 18:32 UTC by Shelnutt2

This lets users manually set tiledb parameters for access the data. Previously this was supported by setting the TileDB-R default context. This increases the flexibility for users by allowing config or context to be passed in.

2022-04-26 19:42 UTC, aaronwolen approved these changes
Thanks @Shelnutt2! I noted a couple minor items.

2022-04-26 19:42 UTC, aaronwolen commented on R/TileDBArray.R
> +      tiledb::tiledb_object_type(self$uri, ctx <- self$ctx) == "ARRAY"
```suggestion
      tiledb::tiledb_object_type(self$uri, ctx = self$ctx) == "ARRAY"
```

2022-04-26 19:42 UTC, aaronwolen commented on R/TileDBArray.R
> +      self$config <- config
Do we need to store the `config` as its own field if it's only used to create the `ctx` below?

2022-04-26 19:42 UTC, aaronwolen commented on R/TileDBArray.R
> +      self$ctx <- ctx
```suggestion
      self$ctx <- ctx %||% tiledb::tiledb_get_context()
```

Could use our infix operator to replace NULLs with a default and remove the lines 32-34.

2022-04-26 21:20 UTC, johnkerl approved these changes
🚢 
with request wording-change @Shelnutt2

2022-04-26 21:20 UTC, johnkerl commented on R/TileDBArray.R
> +      if (!is.null(config) && !is.null(ctx)) stop("Cannot pass a config and context, please choose one")
`Cannot pass both a config and a context -- please specify only one`

2022-04-26 21:20 UTC, johnkerl commented on R/TileDBGroup.R
> +      if (!is.null(config) && !is.null(ctx)) stop("Cannot pass a config and context, please choose one")
ditto above wording

2022-04-26 21:21 UTC, johnkerl commented on R/TileDBArray.R
> +      if (!is.null(config) && !is.null(ctx)) stop("Cannot pass a config and context, please choose one")
also obv CI fail needs looking at -- i can later this evening

2022-04-26 22:29 UTC, johnkerl requested changes
... sorry for change, requesting changes -- from the CI fail i see

```
── Error (test_SCDataset_Seurat.R:36:3): SCDataset can be created from a Seurat object ──
Error in `initialize(...)`: unused argument (context = NULL)
```

which i'll peek at this evening

2022-04-26 22:37 UTC, johnkerl commented
one CI error is fixed by this; need to look at the other:

```
$ gd
diff --git a/R/SCDataset.R b/R/SCDataset.R
index 2c75f9a..8a2640d 100644
--- a/R/SCDataset.R
+++ b/R/SCDataset.R
@@ -72,7 +72,7 @@ SCDataset <- R6::R6Class(
       for (assay in assays) {
         assay_object <- object[[assay]]
         assay_uri <- file_path(self$uri, paste0("scgroup_", assay))
-        scgroup <- SCGroup$new(assay_uri, verbose = self$verbose, config = self$config, context = self$context)
+        scgroup <- SCGroup$new(assay_uri, verbose = self$verbose, config = self$config, ctx = self$context)
         scgroup$from_seurat_assay(assay_object, obs = object[[]])
         self$add_member(scgroup, name = assay)
       }
@@ -206,8 +206,8 @@ SCDataset <- R6::R6Class(
       names(scgroup_uris) <- sub("scgroup_", "", names(scgroup_uris), fixed = TRUE)

       c(
-        lapply(scgroup_uris, SCGroup$new, verbose = self$verbose, config = self$config, context = self$context),
-        lapply(misc_uri, TileDBGroup$new, verbose = self$verbose, config = self$config, context = self$context)
+        lapply(scgroup_uris, SCGroup$new, verbose = self$verbose, config = self$config, ctx = self$context),
+        lapply(misc_uri, TileDBGroup$new, verbose = self$verbose, config = self$config, ctx = self$context)
       )
     },

diff --git a/R/SCGroup.R b/R/SCGroup.R
index 459b404..05dd079 100644
--- a/R/SCGroup.R
+++ b/R/SCGroup.R
@@ -49,8 +49,8 @@ SCGroup <- R6::R6Class(
       uri,
       verbose = TRUE,
       config = NULL,
-      context = NULL) {
-      super$initialize(uri, verbose, config, context)
+      ctx = NULL) {
+      super$initialize(uri, verbose, config, ctx)

       if ("obs" %in% names(self$members)) {
         self$obs <- self$get_member("obs")
```

2022-04-27 00:24 UTC, johnkerl commented
@Shelnutt2 I'll add some pre-commit info to `README.md` as we're all (you & me included!) polyglots these days -- one being `devtools::test()` (after `install.packages("devtools")` once) which will run everything in `tests/testthat/` like the CI job, but locally & quicker / more interactively.

There's also `R CMD check .` which is useful locally pre-push, and which is part of the CI as well.

2022-04-27 00:48 UTC, johnkerl commented
@Shelnutt2 the other CI fail can be addressed by this:

```
diff --git a/tests/testthat/test_TileDBGroup.R b/tests/testthat/test_TileDBGroup.R
index c32ed2e..2acc034 100644
--- a/tests/testthat/test_TileDBGroup.R
+++ b/tests/testthat/test_TileDBGroup.R
@@ -17,10 +17,18 @@ test_that("members can be added and retrieved from a new group", {
   expect_is(grp$tiledb_group(), "tiledb_group")

   expect_equal(grp$count_members(), 0)
+
   objs <- grp$list_objects()
   expect_is(objs, "data.frame")
   expect_equal(nrow(objs), 0)
-  expect_identical(grp$list_members(), objs)
+
+  mems <- grp$list_members()
+  expect_is(mems, "data.frame")
+  expect_equal(nrow(mems), 0)
+
+  # members and objects are not identical --
+  # members is a data.frame with (type, uri, name)
+  # objects is a data.frame with (type, uri)
```

2022-04-27 00:49 UTC, johnkerl commented
commit https://github.com/TileDB-Inc/tiledbsc/pull/47/commits/9878aa1ad483e13bc1568509d8804fa7350d5b42 has both CI-failure fixes as noted above

2022-04-27 00:54 UTC, Shelnutt2 commented on R/TileDBGroup.R
> +    #' @return A `data.frame` with columns `URI`, `TYPE`, and `NAME`.
I was working on this as a second change set, we can remove from this PR (or leave). This was not required for the context/config addition.

2022-04-27 00:54 UTC, johnkerl approved these changes

2022-04-27 00:58 UTC, merged